tasks:
  - name: python installs
    init: |
      sudo apt-get update
      sudo apt-get install -y build-essential libssl-dev uuid-dev libgpgme11-dev
      sudo apt-get install -y squashfs-tools libseccomp-dev wget pkg-config git cryptsetup golang
      export VERSION=3.9.3
      wget https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-${VERSION}.tar.gz
      tar xzf singularity-${VERSION}.tar.gz
      bash install_nf.sh
      cd singularity-${VERSION}
