tasks:
  - name: python installs
    init: |
      sudo apt-get update
      sudo apt-get install -y build-essential libssl-dev uuid-dev libgpgme11-dev squashfs-tools libseccomp-dev wget golang
      wget https://github.com/sylabs/singularity/archive/refs/tags/v3.9.3.tar.gz
      tar xzf v3.9.3.tar.gz
      cd singularity-3.9.3
