tasks:
  - name: python installs
    init: |
      sudo apt-get update
      sudo apt-get install -y build-essential libssl-dev uuid-dev libgpgme11-dev squashfs-tools libseccomp-dev wget golang tar
      wget https://github.com/sylabs/singularity/releases/download/v3.9.3/singularity-3.9.3.tar.gz
      tar xzf singularity-${VERSION}.tar.gz
